FROM golang:alpine

# Copy the code into the container
COPY client-mtls.go .
COPY client-no-mtls.go .

# Copy cert and key
COPY cert.pem .
COPY key.pem .

# Build the application
RUN go build client-mtls.go
RUN go build client-no-mtls.go

# Command to run when starting the container
CMD ["./client"]