FROM golang:alpine

# Copy the code into the container
COPY client-basic.go .

# Copy cert and key
COPY cert.pem .
COPY key.pem .

# Build the application
RUN go build client-basic.go

# Command to run when starting the container
CMD ["./client-basic"]